use_frameworks!

platform :ios, '9.0'

target 'MTCache_Example' do
  pod 'MTCache', :path => '../'
  pod 'YYModel', '~> 1.0.4'
  pod 'YYCache', '~> 1.0.4'
  target 'MTCache_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
